# Generated by Django 4.0.3 on 2022-08-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_interest_open_response_personinterest_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interestcategory'),
        ),
        migrations.AlterField(
            model_name='personinterest',
            name='detail',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
