# Generated by Django 4.0.3 on 2022-08-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_interest_category_alter_personinterest_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='category',
        ),
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='users.interestcategory'),
        ),
    ]
