# Generated by Django 4.0.3 on 2022-04-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
