# Generated by Django 4.0.3 on 2022-04-05 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapi', '0002_alter_hobby_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('school', models.CharField(max_length=60)),
                ('major', models.CharField(max_length=60)),
                ('religion', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='hobby',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tribeapi.person'),
            preserve_default=False,
        ),
    ]
