# Generated by Django 4.0.2 on 2022-06-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tribeapi', '0003_person_hobby_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='pid',
        ),
        migrations.CreateModel(
            name='PersonHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='tribeapi.hobby')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='tribeapi.person')),
            ],
        ),
    ]
